# Generated by Django 4.1 on 2022-09-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("new", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="house",
            field=models.TextField(max_length=100, null=True),
        ),
    ]
